FROM maven:3.9.11-eclipse-temurin-17 AS build
ARG MODULE
WORKDIR /workspace
COPY . .
RUN mvn -pl ${MODULE} -am package -DskipTests -Dskip.admin.build=true

FROM eclipse-temurin:17-jre-jammy
ARG MODULE
WORKDIR /app
COPY --from=build /workspace/${MODULE}/target/*.jar /app/app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
