<template><div><div class="page-heading"><div><h1>灰度用户与测试余额</h1><p>余额调整仅用于灰度运营，所有操作均写入资金流水和审计日志。</p></div><el-button :loading="loading" @click="load">刷新</el-button></div><el-card shadow="never"><el-table v-loading="loading" :data="items" stripe><el-table-column prop="userId" label="用户ID" width="150"/><el-table-column prop="phoneNumber" label="手机号"/><el-table-column prop="name" label="姓名"/><el-table-column label="实名" width="90"><template #default="{row}"><el-tag :type="row.verified?'success':'warning'">{{row.verified?'已实名':'未实名'}}</el-tag></template></el-table-column><el-table-column label="测试余额"><template #default="{row}">¥{{(row.balanceCents/100).toFixed(2)}}</template></el-table-column><el-table-column label="操作" width="150"><template #default="{row}"><el-button link type="primary" @click="adjust(row)">调整余额</el-button></template></el-table-column></el-table></el-card></div></template>
<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { ElMessage, ElMessageBox } from 'element-plus'; import { api } from '@/api/client';
interface UserRow{userId:number;phoneNumber?:string;name?:string;verified:boolean;balanceCents:number}
const loading=ref(false);const items=ref<UserRow[]>([]);
async function load(){loading.value=true;try{const p=await api.request<{items:UserRow[]}>('/api/v2/ops/admin/users?page=0&size=100','GET');items.value=p.items||[]}finally{loading.value=false}}
async function adjust(row:UserRow){const amount=await ElMessageBox.prompt(`当前测试余额 ¥${(row.balanceCents/100).toFixed(2)}。输入变动金额，正数发放、负数扣回。`,'调整测试余额',{inputPattern:/^-?\d+(\.\d{1,2})?$/,inputErrorMessage:'请输入正确金额',confirmButtonText:'下一步',cancelButtonText:'取消'});const reason=await ElMessageBox.prompt('必须填写调整原因，提交后不可删除','确认资金操作',{inputValidator:v=>!!String(v||'').trim()||'必须填写原因',confirmButtonText:'确认提交',cancelButtonText:'取消',type:'warning'});const deltaCents=Math.round(Number(amount.value)*100);await api.request(`/api/v2/ops/admin/users/${row.userId}/balance`,'POST',{deltaCents,reason:reason.value,idempotencyKey:`admin-${row.userId}-${Date.now()}`});ElMessage.success('测试余额已调整');await load()}
onMounted(load);
</script><style scoped>.page-heading{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:20px}.page-heading h1{margin:0;font-size:24px}.page-heading p{margin:6px 0 0;color:#64748b}</style>
